[package]
name = "certstream"
version = "0.1.0"
authors = ["Bradford D. Boyle <bradford.d.boyle@gmail.com>"]

readme = "README.md"

license = "MIT"

[dependencies]
serde_json = "1.0"
websocket = "0.20.2"
